json.id place.id
json.trip_id place.trip_id
json.address place.address
json.name place.name
json.description place.description
json.start_time place.start_time
json.end_time place.end_time
json.lat place.lat
json.long place.long
json.trip place.trip